/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAddRouteImport } from './routes/_authenticated/add'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedShelfRouteImport } from './routes/_authenticated/shelf'
import { Route as AuthenticatedMemberUserIdRouteImport } from './routes/_authenticated/member.$userId'
import { Route as AuthenticatedWineWineIdRouteImport } from './routes/_authenticated/wine.$wineId'
import { Route as AuthenticatedEntryEntryTypeEntryIdRouteImport } from './routes/_authenticated/entry.$entryType.$entryId'
import { Route as ApiPublicHooksPurgePhotosRouteImport } from './routes/api/public/hooks/purge-photos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAddRoute = AuthenticatedAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShelfRoute = AuthenticatedShelfRouteImport.update({
  id: '/shelf',
  path: '/shelf',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemberUserIdRoute =
  AuthenticatedMemberUserIdRouteImport.update({
    id: '/member/$userId',
    path: '/member/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWineWineIdRoute = AuthenticatedWineWineIdRouteImport.update({
  id: '/wine/$wineId',
  path: '/wine/$wineId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntryEntryTypeEntryIdRoute =
  AuthenticatedEntryEntryTypeEntryIdRouteImport.update({
    id: '/entry/$entryType/$entryId',
    path: '/entry/$entryType/$entryId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksPurgePhotosRoute =
  ApiPublicHooksPurgePhotosRouteImport.update({
    id: '/api/public/hooks/purge-photos',
    path: '/api/public/hooks/purge-photos',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/add': typeof AuthenticatedAddRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/shelf': typeof AuthenticatedShelfRoute
  '/member/$userId': typeof AuthenticatedMemberUserIdRoute
  '/wine/$wineId': typeof AuthenticatedWineWineIdRoute
  '/entry/$entryType/$entryId': typeof AuthenticatedEntryEntryTypeEntryIdRoute
  '/api/public/hooks/purge-photos': typeof ApiPublicHooksPurgePhotosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/add': typeof AuthenticatedAddRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/shelf': typeof AuthenticatedShelfRoute
  '/member/$userId': typeof AuthenticatedMemberUserIdRoute
  '/wine/$wineId': typeof AuthenticatedWineWineIdRoute
  '/entry/$entryType/$entryId': typeof AuthenticatedEntryEntryTypeEntryIdRoute
  '/api/public/hooks/purge-photos': typeof ApiPublicHooksPurgePhotosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accessibility': typeof AccessibilityRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/add': typeof AuthenticatedAddRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/shelf': typeof AuthenticatedShelfRoute
  '/_authenticated/member/$userId': typeof AuthenticatedMemberUserIdRoute
  '/_authenticated/wine/$wineId': typeof AuthenticatedWineWineIdRoute
  '/_authenticated/entry/$entryType/$entryId': typeof AuthenticatedEntryEntryTypeEntryIdRoute
  '/api/public/hooks/purge-photos': typeof ApiPublicHooksPurgePhotosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/add'
    | '/feed'
    | '/shelf'
    | '/member/$userId'
    | '/wine/$wineId'
    | '/entry/$entryType/$entryId'
    | '/api/public/hooks/purge-photos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/add'
    | '/feed'
    | '/shelf'
    | '/member/$userId'
    | '/wine/$wineId'
    | '/entry/$entryType/$entryId'
    | '/api/public/hooks/purge-photos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accessibility'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/add'
    | '/_authenticated/feed'
    | '/_authenticated/shelf'
    | '/_authenticated/member/$userId'
    | '/_authenticated/wine/$wineId'
    | '/_authenticated/entry/$entryType/$entryId'
    | '/api/public/hooks/purge-photos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessibilityRoute: typeof AccessibilityRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiPublicHooksPurgePhotosRoute: typeof ApiPublicHooksPurgePhotosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/add': {
      id: '/_authenticated/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AuthenticatedAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shelf': {
      id: '/_authenticated/shelf'
      path: '/shelf'
      fullPath: '/shelf'
      preLoaderRoute: typeof AuthenticatedShelfRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/member/$userId': {
      id: '/_authenticated/member/$userId'
      path: '/member/$userId'
      fullPath: '/member/$userId'
      preLoaderRoute: typeof AuthenticatedMemberUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wine/$wineId': {
      id: '/_authenticated/wine/$wineId'
      path: '/wine/$wineId'
      fullPath: '/wine/$wineId'
      preLoaderRoute: typeof AuthenticatedWineWineIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entry/$entryType/$entryId': {
      id: '/_authenticated/entry/$entryType/$entryId'
      path: '/entry/$entryType/$entryId'
      fullPath: '/entry/$entryType/$entryId'
      preLoaderRoute: typeof AuthenticatedEntryEntryTypeEntryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/purge-photos': {
      id: '/api/public/hooks/purge-photos'
      path: '/api/public/hooks/purge-photos'
      fullPath: '/api/public/hooks/purge-photos'
      preLoaderRoute: typeof ApiPublicHooksPurgePhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddRoute: typeof AuthenticatedAddRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedShelfRoute: typeof AuthenticatedShelfRoute
  AuthenticatedMemberUserIdRoute: typeof AuthenticatedMemberUserIdRoute
  AuthenticatedWineWineIdRoute: typeof AuthenticatedWineWineIdRoute
  AuthenticatedEntryEntryTypeEntryIdRoute: typeof AuthenticatedEntryEntryTypeEntryIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddRoute: AuthenticatedAddRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedShelfRoute: AuthenticatedShelfRoute,
  AuthenticatedMemberUserIdRoute: AuthenticatedMemberUserIdRoute,
  AuthenticatedWineWineIdRoute: AuthenticatedWineWineIdRoute,
  AuthenticatedEntryEntryTypeEntryIdRoute:
    AuthenticatedEntryEntryTypeEntryIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessibilityRoute: AccessibilityRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiPublicHooksPurgePhotosRoute: ApiPublicHooksPurgePhotosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
